### ISSUE TITLE
make required folders

### ISSUE THREAD

**Issue by nsheff** [databio/bedshift#31]
if a folder for an output doesn't exist, it gives:

```
## [1 of 216] sample: add1_0; pipeline: bedshift_run
'pipestat' not found in 'looper' section of the project configuration file. Using defaults.
Could not determine pipestat namespace. Caught exception: AttributeError('pipestat_config')
Calling pre-submit function: refgenconf.looper_refgenie_plugin
Writing script to /home/nsheff/code/bedshift_paper/fig/code/pep_project_5trials/looper_output/submission/bedshift_run_add1_0.sub
Job script (n=1; 0.00Gb): looper_output/submission/bedshift_run_add1_0.sub
Compute node: zither
Start time: 2021-03-23 17:47:32
Welcome to bedshift version 1.1.0-dev
Shifting file: '/home/nsheff/encode_tfbs/regions//wgEncodeAwgTfbsUwHek293CtcfUniPk.narrowPeak'
Params:
  chrom.sizes file: /home/nsheff/code/refgenie_sandbox/alias/hg19/fasta/default/hg19.chrom.sizes
  shift:
    shift rate: 0.0
    shift mean distance: 0.0
    shift stdev: 150.0
    shift regions from file: None
  add:
    rate: 0.1
    add mean length: 320.0
    add stdev: 30.0
    add regions from file: /home/nsheff/code/bedshift_paper/fig/code/ALL_1000overlap_300files_segments.bed
    valid regions: None
  cut rate: 0.0
  drop rate: 0.0
    drop regions from file: None
  merge rate: 0.0
  outputfile: /home/nsheff/bedshifted//0/add1_0.bed
  repeat: 100
  yaml_config: None

        4733 regions changed in total.

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/bedshift", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/bedshift/bedshift.py", line 571, in main
    bedshifter.to_bed(modified_outfile)
  File "/home/nsheff/.local/lib/python3.8/site-packages/bedshift/bedshift.py", line 465, in to_bed
    self.bed.to_csv(outfile_name, sep='\t', header=False, index=False, float_format='%.0f')
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 185, in save
    f, handles = get_handle(
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: '/home/nsheff/bedshifted//0/rep1_add1_0.bed'
```

should we just auto-create said folder? otherwise I have to create all these manually...

**Comment by nsheff** [comment]
I could also solve this by adding this to the command template in the pipeline interface:

```
command_template: >
    mkdir -p {sample.output_dir}/{sample.trial};
```

but maybe better to just handle at the bedshift level?

**Comment by aaron-gu** [comment]
I thought it was more polite to not create folders in the tool. `mkdir` in looper seems good to me
