### ISSUE TITLE
Passing list-likes to .loc or [] with any missing labels is no longer supported.

### ISSUE THREAD

**Issue by nsheff** [databio/bedshift#32]
```
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/bedshift", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/bedshift/bedshift.py", line 555, in main
    n = bedshifter.all_perturbations(args.addrate, args.addmean, args.addstdev,
  File "/home/nsheff/.local/lib/python3.8/site-packages/bedshift/bedshift.py", line 443, in all_perturbations
    n += self.add_from_file(addfile, addrate)
  File "/home/nsheff/.local/lib/python3.8/site-packages/bedshift/bedshift.py", line 170, in add_from_file
    add_df = df.loc[add_rows].reset_index(drop=True)
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/nsheff/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1315, in _validate_read_indexer
    raise KeyError(
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Int64Index([0], dtype='int64'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```

```
version info:
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 

In [2]: pandas.__version__
Out[2]: '1.1.3'
```

**Comment by nsheff** [comment]
@aaron-gu let me know if that is OK.

**Comment by aaron-gu** [comment]
This is a weird error that I'm not sure is related to `.loc`. I am using version `1.2.3` and haven't seen this issue.

What was your `--addfile` that you used?

**Comment by nsheff** [comment]
it was the one from the file you had in the repo. and it only happened on 1 of the iterations

**Comment by aaron-gu** [comment]
Do you happen to have the bedshift command you used?

From this error `The following labels were missing: Int64Index([0], dtype='int64')`,  my suspicion is that the problem is with the DataFrame, and potentially caused by a previous perturbation (shift?)

What does `reindex` do? I feel like it doesn't solve the problem and might hide the bug the next time it occurs.

**Comment by nsheff** [comment]
I was running the pep_project_5trials you created. it was in the first sample. in that project. so -- can't be caused by another perturbation because it was add only.

**Comment by aaron-gu** [comment]
OK I can reproduce it. It looks like a bug related to the header line of `--addfile`. PR coming
